language: cpp

install:
  # pip cannot install Conan without these upgrades
  # CMake >= 3.15 is required
  - python3 -m pip install --upgrade pip setuptools
  - python3 -m pip install conan cmake

  # fail if we can't run Conan
  - conan --version

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc
            - python3-pip
      after_script:
        - bash <(curl -s https://codecov.io/bash)

    - os: linux
      dist: bionic
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      addons: { apt: { packages: ['python3-pip'] } }

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE ../
  - cmake --build . -- -j2
  - ctest -j2