language: cpp

install:
  # pip cannot install Conan without these upgrades
  # CMake >= 3.15 is required
  - python3 -m pip install --upgrade pip setuptools
  - python3 -m pip install conan cmake

  # fail if we can't run Conan
  - conan --version

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc
            - python3-pip
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -- -j2